services:
  caddy:
    image: abiosoft/caddy
    ports:
      - 127.0.0.1:8334:8334
    environment:
       - ACME_AGREE=true
    volumes:
      - ./docker/Caddyfile:/etc/Caddyfile
  ord:
    build:
      context: .
      dockerfile: docker/ord.Dockerfile
    ports:
      - "127.0.0.1:8080:80" # HTTP PORT
    environment:
      - RUST_LOG=trace
    volumes:
      - /mnt/btcdata:/btcdata # Bitcoin node data dir
      - /mnt/orddata:/orddata # Ord side car data dir
    command: /usr/src/myapp/target/release/ord --data-dir /orddata --bitcoin-data-dir /btcdata --rpc-url http://btcd:8334 server
  btcd:
    build:
      context: docker/btcd
    ports:
      - 8333:8333
    volumes:
      - /mnt/btcdata:/btcdata
      - ./docker/btcd.conf:/config
    command: btcd -C /config --notls
