services:
  proxy:
    build:
      context: docker/proxy
    ports:
      - 127.0.0.1:8334:8334
    environment:
       - LISTEN_ADDR=0.0.0.0
       - LISTEN_PORT=8334
       - REMOTE_ADDR=btcd
       - REMOTE_PORT=8334
  ord:
    build:
      context: .
      dockerfile: docker/ord.Dockerfile
    ports:
      - "127.0.0.1:8080:80" # HTTP PORT
    environment:
      - RUST_LOG=info
    volumes:
      - /mnt/btcdata:/btcdata # Bitcoin node data dir
      - /mnt/orddata:/orddata # Ord side car data dir
    command: /usr/src/myapp/target/release/ord --data-dir /orddata --bitcoin-data-dir /btcdata --rpc-url http://proxy:8334 server
  btcd:
    build:
      context: docker/btcd
    ports:
      - 8333:8333
      - 127.0.0.1:8335:8334
    volumes:
      - /mnt/btcdata:/btcdata
      - ./docker/btcd.conf:/config
    command: btcd -C /config --notls
